- name: Deploy to OSS
    uses: saltbo/uptoc@master
    with:
      driver: oss
      region: cn-hangzhou
      bucket: ${{ secrets.bucket }}
      exclude: data.json
    env:
      UPTOC_UPLOADER_AK: ${{ secrets.ACCESS_KEY_ID }}
      UPTOC_UPLOADER_SK: ${{ secrets.ACCESS_KEY_SECRET }}
